# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  echo-hello:
    name: echo-hello
    runs-on: ubuntu-latest
    steps:
      - uses: docker://alpine:3.11
        with:
          entrypoint: /bin/echo
          args: Hello, World kokkkookokokk!!
